language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
services:
  - memcached
before_install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U setuptools; fi
install: python setup.py install
before_script: pip install -r test-requirements.txt
script:
  - flake8
  - nosetests
